apiVersion: v1
kind: Service
metadata:
  name: my-clusterIP-service
  labels:
    type: cluster-service-object
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: frontend-pod