apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
  labels:
    type: nodeport-service-object
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
  selector:
    name: frontend-pod