apiVersion: v1
kind: Pod
metadata:
  name: my-pod-config
  labels:
    name: frontend-pod
    tier: presentation
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      env:
        - name: password
          value: mysecretpassword